### ISSUE TITLE
add md5sum on release

### ISSUE THREAD

**Issue by asuras-development** [knoxfighter/arcdps-killproof.me-plugin#1]
Hey there, I wrote a script to update my arcdps and addons. I would like to include your plugin. Adding a latest tag for a steady download url (without any version number) and a file with the md5sum would help me alot to check if updates are necessary.

**Comment by knoxfighter** [comment]
I have added a .sha file, that contains an sha256 of the dll. I added that to the latest realease only, i will add it to every new release.
As alternative, you can get the full list of all releases and safe your current installed version and check if the newest version is higher than that.

**Comment by asuras-development** [comment]
Thanks, after some hours I finally got it to work with my script. I ran into an issue with curl treating the sha256-hash as a binary file for some reason. I am not sure if the problem is on my or your side, because other downloaded md5-hash files (e.g. combat-mechanics or arc itself) are correctly treated as text files. This causes problems in comparing the values. Luckily I found a workaround.

Github's url management is a bit wacky. There is always a url pointer to the files from the latest release, but took me some time to find it!

**Comment by knoxfighter** [comment]
I would like to remove the sha's from the releases, they are downloaded a lot and people get confused by them.
In future releases a correct versioning is added to the dll (in the form of VS_VERSION_INFO).
Therefore the release after the next one will not contain the sha anymore. This counts for all my plugins!!

**Comment by knoxfighter** [comment]
sha file is not added to the release anymore!

Please use VS_VERSION_INFO to find out which dll version is used.

**Comment by asuras-development** [comment]
Well how can I configure my update script to only download the new release if it is actually a new release? I used the sha-value to check if the file on the server matches the installed file and redownload if the sums are different. If I want to compare the VS_VERSION_INFO, I will have to download the dll-file (which is a lot bigger) everytime I run my update script - or to ease things up, just download the current latest release of every plugin every time I start gw.
I use a specific download url which directly points to the file of the latest release tagged version - so I don't have to figure out the latest version number every time.
