### ISSUE TITLE
Launch error `The procedure entry point ...` or ingame `Failed to load`.

### ISSUE THREAD

**Issue by Olian04** [knoxfighter/arcdps-killproof.me-plugin#10]
I just updated to 2.6 (clean install, deleted old dll and downloaded 2.6).
When I launch the game I get this error.

![](https://i.imgur.com/9mMSD4c.png)

**Comment by sabin95** [comment]
I have the same problem

**Comment by sabin95** [comment]
![image_2021-09-17_203142](https://user-images.githubusercontent.com/6749023/133829973-3fe498fe-39bb-43fe-84a4-5e5791f26f2d.png)
And this is the error in the game

**Comment by knoxfighter** [comment]
Install the latest c++ redistributable: https://support.microsoft.com/en-gb/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0

Direct Download: https://aka.ms/vs/16/release/vc_redist.x64.exe

**Comment by sabin95** [comment]
Installed https://aka.ms/vs/16/release/vc_redist.x64.exe and all good now.
Thanks!

**Comment by yolo12345asd** [comment]
Thanks, i had the same problem and solved by downloading latest c++.

**Comment by Erathy** [comment]
Hi,
Had this error, did the upgrade and now the moment I activate killproof.me table game crashes.

**Comment by knoxfighter** [comment]
For some reason it is only solving for some, i am currently working on a fix.

**Comment by Mitarex-git** [comment]
Hi,
Confirm, full game crash when trying to open the killproof table after installing the redistributable (was getting the entry point error before). No error message, just kills it instantly.

**Comment by knoxfighter** [comment]
New release v2.6.1 will fix that. It also is removing the dependency to that new redistributable.
