### ISSUE TITLE
Add setting to disable new update notification

### ISSUE THREAD

**Issue by gbaso** [knoxfighter/arcdps-killproof.me-plugin#11]
I play GW2 on Linux using lutris. I use arcdps and several other plugins without issues, but the killproof plugin v2.6.0 doesn't work, it just shows an error in the arcdps log on startup.
Note that up to this point I did not have the VC++ 2015-2019 libraries installed. After installing the libraries via wintricks, the startup error doesn't appear anymore, but as soon as I open the killproof window the whole game crashes.

I understand that this is not a supported case and I'm not asking for a fix to this problem, I downgraded to v2.5.2 and it works fine.

However, now every time I start the game I get a message telling me a new version is available. I'd like to be able to disable this notification (and please backport this to v2.5).

**Comment by knoxfighter** [comment]
I understand your request and am unsure if i will add such a thing. Since that error is not only a wine/linux problem, i am currently implementing a fix for that. So the release v2.6.1 will contain a fix for it.

**Comment by knoxfighter** [comment]
Update v2.6.1 released, it should work now.

**Comment by gbaso** [comment]
Fix confirmed, thanks!

Also thanks for considering supporting linux :)
