### ISSUE TITLE
Opening/closing accounts that have the same text are all opened/closed at the same time

### ISSUE THREAD

**Issue by Kaloell** [knoxfighter/arcdps-killproof.me-plugin#12]
If 2 linked accounts are in the same squad "expanding" one of them expands both.
If A and B are linked, expanding one results in
```
> A
> B
```
to 
```
> A
  B
  Overall
> B
  A
  Overall
```
with 1 click.

**Comment by knoxfighter** [comment]
I see it problematic, when two people, that have their account linked to each other, are in the same squad. 
But i will fix that error nonetheless :)

**Comment by knoxfighter** [comment]
This happens to all accounts that are added in the same second. This bug has nothing to do with linked accounts.

**Comment by knoxfighter** [comment]
Fixed in 2.7.0
