### ISSUE TITLE
Subgroup as a sortable column

### ISSUE THREAD

**Issue by GeneratedNickname** [knoxfighter/arcdps-killproof.me-plugin#15]
Would be great if we had a subgroup column that we could sort by. Most pugs put accepted players into subs 2 and 3, so you identify new joiners more easily.

**Comment by knoxfighter** [comment]
Currently you can sort by time, therefore you can have the latest joined at the top or the bottom. But i will add a subgroup column as well.

**Comment by knoxfighter** [comment]
Added in v.2.8.1
