### ISSUE TITLE
Forgets settings when restarting the game

### ISSUE THREAD

**Issue by Iiridayn** [knoxfighter/arcdps-killproof.me-plugin#22]
Might be the same issue as knoxfighter/GW2-ArcDPS-Boon-Table#15, same solution might work.

I would attempt it myself, but the little bit of searching I've done on trying to use a MS project file to build on Linux has scared me away.

**Comment by knoxfighter** [comment]
The latest version of the boon table is not saved the same way the Boon-Table, therefore this error is definitely a different one. My guess would be a problem with the permissions. Try to fix it, by deleting the `arcdps_killproof.me.json` file, so it gets recreated.

**Comment by Iiridayn** [comment]
Sorry, looks like the issue might have been a failed save due to a client crash. Was too excited about the boon table fix :).
