### ISSUE TITLE
Auto update to 2.5.0 causes "Bad Image" error

### ISSUE THREAD

**Issue by Olian04** [knoxfighter/arcdps-killproof.me-plugin#7]
After launching the game I got a message saying that a new version was available and that it could be auto updated should I want to. It said that the auto update was successful and to restart the game. Upon which I got this `Bad Image` error. 

![](https://i.imgur.com/JZxwOpg.png)

The faulty dll: https://drive.google.com/file/d/1jSY0dQtft5QIcBRNo4_POuoytZZemO7C/view

Updated from version 2.4.0 to 2.5.0.
Windows 10 Home Edition version 19041.1052

**Comment by danifischer** [comment]
Same here.

Workaround is downloading the version from the releases manually.

**Comment by knoxfighter** [comment]
Yes, please update manually, for some reason the autoupdate feature broke :(

**Comment by knoxfighter** [comment]
First look at it: The downloaded file is slightly bigger than the correct file.
github file: 1397 kB
broken file: 1403 kB

**Comment by knoxfighter** [comment]
Fixed in next version (has to manually updated obviously)
