### ISSUE TITLE
can't remove all manually added users

### ISSUE THREAD

**Issue by hk3wx** [knoxfighter/arcdps-killproof.me-plugin#8]
As the tittle says.

**Comment by knoxfighter** [comment]
There is a clear button on the top, that will remove all manually added accounts from the list

**Comment by Olian04** [comment]
I've also had issues with this before. Sometimes the clear button just doesn't work.

**Comment by knoxfighter** [comment]
First of all, it should be impossible to show up twice in the list. If that is possible that is a bug on it's own xD

I think what happens here is: Users that are already tracked as "automatic" cannot be removed with the clear button.

**Comment by knoxfighter** [comment]
Both bugs fixed in v2.5.1 :)
